# Generated by Django 4.1.2 on 2025-12-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='생성(등록)일시')),
                ('ip', models.CharField(max_length=256, verbose_name='403 IP')),
            ],
            options={
                'db_table': 'block_ip',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='생성(등록)일시')),
                ('type', models.CharField(default='', max_length=256, verbose_name='구분')),
                ('product_name', models.CharField(default='', max_length=256, verbose_name='제품명')),
                ('keyword', models.CharField(default='', max_length=256, verbose_name='키워드')),
                ('group', models.CharField(default='', max_length=256, verbose_name='그룹')),
            ],
            options={
                'verbose_name': '키워드',
                'db_table': 'keyword',
            },
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='생성(등록)일시')),
                ('product_name', models.CharField(default='', max_length=256, verbose_name='제품명')),
                ('keyword', models.CharField(default='', max_length=256, verbose_name='키워드')),
                ('part', models.CharField(default='', max_length=256, verbose_name='파트')),
                ('url', models.CharField(default='', max_length=1024, verbose_name='url')),
            ],
            options={
                'verbose_name': 'URL',
                'db_table': 'url',
            },
        ),
    ]
