# Generated by Django 4.1.2 on 2026-02-24 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_add_keyword_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='priority',
            field=models.CharField(default='', max_length=256, verbose_name='우선순위'),
        ),
        migrations.AddField(
            model_name='url',
            name='content_type',
            field=models.CharField(default='', max_length=256, verbose_name='원고형태'),
        ),
        migrations.AddField(
            model_name='url',
            name='conversion_keyword',
            field=models.CharField(default='', max_length=256, verbose_name='전환키워드'),
        ),
    ]
